This is a test = sed

CXX = c++

CXXFLAGS = -Wall -Wextra -Werror -std=c++98

SRCS = main.cpp
	
$(This is a test): $(SRCS)
	$(CXX) $(CXXFLAGS) $(SRCS) -o $(This is a test)

all: $(This is a test)

clean:
	rm -f $(OBJS)
	
fclean: clean
	rm -f $(This is a test)
	
re: fclean all

.PHONY: all clean fclean re
